#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "material"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    relativenumber = false

[[layers]]
  name = "colorscheme"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
  name = "lang#java"

[[layers]]
  name = "lang#oython"

[[layers]]
  name = "lsp"
  filetypes = [
    "java"
  ]
  [layers.override_cmd]
    java = [
    "java",
    "-Declipse.application=org.eclipse.jdt.ls.core.id1",
    "-Dosgi.bundles.defaultStartLevel=4",
    "-Declipse.product=org.eclipse.jdt.ls.core.product",
    "-Dlog.protocol=true",
    "-Dlog.level=NONE",
    "-noverify",
    "-Xmx4G",
    "-jar",
    "/usr/lib/eclipse/plugins/org.eclipse.equinox.launcher_1.6.0.v20200915-1508.jar",
    "-configuration",
    "/usr/lib/eclipse/configuration/config.ini",
    "-data",
    "/home/smsag_000/.cache/javalsp"
    ]

[[layers]]
  name = "lang#kotlin"

[[layers]]
  name = "lang#python"
  python_interpreter = "/usr/bin/env python"

[[layers]]
  name = "lang#go"

[[layers]]
  name = "format"

[[layers]]
  name = 'git'
[[layers]]
  name = 'VersionControl'

[[layers]]
  name = "lang#c"
  enable_clang_syntax_highlight = true
